---
title: "qualtrics_cleaning"
author: "Ethan Tenison"
date: "`r format(Sys.Date(), '%B %d, %Y') `"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

# Qualtrics data cleaning 

```{r libraries}

library(tidyverse)
library(qualtRics)
library(conflicted)
library(janitor)
library(ggmap)

conflict_prefer("filter", "dplyr")

```

### Data pull 

```{r pull}

# Connecting to the Qualtrics API
qualtrics_api_credentials(
api_key = Sys.getenv("qualtrics_key"), 
base_url = "ca1.qualtrics.com"
)

#Pulling list of surveys
surveys <- all_surveys() 
#Finding the row index for organization and student surveys
survey_number <- which(surveys$name=="PT 2050 ENGOs in Texas - Final", arr.ind=TRUE)
#Fetching the Survey Contents 
df_raw <- fetch_survey(surveyID = surveys$id[survey_number], force_request = TRUE)

```

### Trimming data 

```{r trimming}


df <- df_raw |> 
  clean_names() |> 
  #close to 100 didn't finish 
  filter(finished != FALSE) |> 
  select(-c(start_date:user_language)) |>
  filter(q1_2 != "lll")

```


### Geomapping

```{r simple_map, echo=FALSE}


df2 <- df |>
  filter(q7_21 == "Yes",!is.na(q7_18)) |>
  mutate(lon = NA, 
         lat = NA,
         # Many address were not written using the right syntax 
         q7_18 = case_when( 
           q7_18 == "3710 Cedar St., Suite #230, Austin, Texas, 78705" ~
             "3710 Cedar St, Austin, TX 78705",
           q7_18 == "2186 Jackson Keller Road #533, San Antonio Tx 78213" ~
             "2186 Jackson Keller Road, San Antonio, TX 78213",
           q7_18 == "PO Box 140650" ~
             "PO Box 140650, Dallas, TX 75214",
           q7_18 == "2921 East 17th Street, Building D, Ste #1, Austin Texas 78702" ~
             "2921 East 17th Street, Austin, TX 78702",
           q7_18 == "801 S Fillmore St. #700  Amarillo/Texas/79101" ~
             "801 S Fillmore, Amarillo, TX 79101",
           q7_18 == "P.O. Box 685261" ~
             "Po Box 685261, Austin, TX 78768",
           TRUE ~ q7_18
         ))

#Geomapping 
geocodes <- geocode(as.character(df2$q7_18))
df2[,204:205] <- geocodes

```


```{r leaflet}
library(leaflet)

m <- leaflet(df2) |> 
  addTiles() |> 
  addMarkers(lng = df2$lon, lat = df2$lat)
m

```

# Data minus network 

```{r data_nonetwork}


df3 <- df2 |>
  #Removing network questions
  select(-c(starts_with("q3"))) |>
  select(-c(starts_with("q6"))) |>
  #mostly blank data
  select(-c(q1_3:q1_6, q8_5)) |>
  mutate(
    #collapsing the secondary obj
    across(q2_3_4:q2_3_8, ~ replace_na(., "")),
    q2_3 = paste0(q2_3_4, ",", q2_3_5,
                  ",", q2_3_6, ",", q2_3_7, ",", q2_3_8),
    q2_3 = gsub("^,+|,+$", "", q2_3),
    q2_3 = gsub(",,", ", ", q2_3),
    q2_3 = gsub(",", ", ", q2_3)
  ) |>
  #removing ind secondary columns
  select(-c(q2_3_4:q2_3_8)) |>
  #Collapsing types of work columns
  mutate(
    across(q2_5_10:q2_5_11_text, ~ replace_na(., "")),
    q2_5 = paste0(
      q2_5_10,",",q2_5_5,",",q2_5_4,",", q2_5_6,",",q2_5_9,",",q2_5_1,",",
      q2_5_2,",",q2_5_7,",",q2_5_8,",",q2_5_12,",",q2_5_3,",",q2_5_11,",",
      q2_5_11_text,","
    ),
    q2_5 = gsub("^,+|,+$", "", q2_5),
    q2_5 = gsub(",+", ", ", q2_5)) |> 
  select(-c(q2_5_10:q2_5_11_text)) |> 
  #Collapsing extreme weather 
  mutate(
    across(q4_2_1:q4_2_7_text, ~ replace_na(., "")),
    q4_2 = paste0(
      q4_2_1,",",q4_2_2,",",q4_2_5,",",q4_2_3,",",q4_2_4,",",q4_2_6,",",
      q4_2_7,",",q4_2_7_text
    ),
    q4_2 = gsub("^,+|,+$", "", q4_2),
    q4_2 = gsub(",+", ", ", q4_2)) |> 
  select(-c(q4_2_1:q4_2_7_text)) |> 
  #collapsing results of extreme weather q4_5
  mutate(
    across(q4_5_1:q4_5_10, ~ replace_na(., "")),
    q4_5 = paste0(
      q4_5_1,",",q4_5_2,",",q4_5_5,",",q4_5_3,",",q4_5_4,",",q4_5_6,",",
      q4_5_7,",",q4_5_8,",", q4_5_9,",", q4_5_10,","
    ),
    q4_5 = gsub("^,+|,+$", "", q4_5),
    q4_5 = gsub(",+", ", ", q4_5)) |> 
  select(-c(q4_5_1:q4_5_10)) |> 
#collapsing results of direct assistance q4_6
  mutate(
    across(q4_6_1:q4_6_4, ~ replace_na(., "")),
    q4_6 = paste0(
      q4_6_1,",",q4_6_2,",",q4_6_3,",",q4_6_4
    ),
    q4_6 = gsub("^,+|,+$", "", q4_6),
    q4_6 = gsub(",+", ", ", q4_6)) |> 
  select(-c(q4_6_1:q4_6_4)) |> 
  #collapsing results of covid impact q4_6
  mutate(
    across(q4_6_1:q4_6_4, ~ replace_na(., "")),
    q4_6 = paste0(
      q4_6_1,",",q4_6_2,",",q4_6_3,",",q4_6_4
    ),
    q4_6 = gsub("^,+|,+$", "", q4_6),
    q4_6 = gsub(",+", ", ", q4_6)) |> 
  select(-c(q4_6_1:q4_6_4))

```

